renesas: common: emmc: increase timeout waiting for CMD1_SEND_OP_COND response
After getting random boot failures with the error message:
ERROR:   BL2: emmc err:func_no=0x4 code=0x10
I found, that the timeout for the loop waiting for response to the
CMD1 (SEND_OP_COND) command was too short for the eMMC in our board.
The eMMC would require up to 364ms (after the eMMC contents has been
changed before power off) rather than the max. 300 allowed by
the driver.

Increase the wait time to 3000ms and print a more meaningful error
message in case of failure.